server:
  port: 8082

spring:
  application:
    name: fund-proxy-2
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: false
            maxAge: 86400
      routes:
        - id: fund-service-route
          uri: lb://fund-service-cluster2
          predicates:
            - Path=/api/**
          filters:
            - name: RequestSize
              args:
                maxSize: 5MB
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
    loadbalancer:
      configurations: default
      ribbon:
        enabled: false
    discovery:
      client:
        simple:
          instances:
            fund-service-cluster2:
              - instanceId: fund-service-3
                uri: http://localhost:7003
              - instanceId: fund-service-4
                uri: http://localhost:7004

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: INFO
    com.example.proxy: DEBUG
